// Dati generati da tools/build_data.py — non modificare a mano, rigenerare dallo script.
const GAMES = [
  {
    "slug": "21-giochi-minuti",
    "titolo": "21 Giochi Minuti",
    "giocatori": "2+",
    "giocatori_min": 2,
    "giocatori_max": 99,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Ventuno giochi diversi in un'unica scatola, ognuno spiegabile e giocabile in un minuto scarso: si può cominciare a giocare prima ancora di essersi seduti bene. Perfetto quando non si sa cosa si vuole giocare, o quando c'è solo pochissimo tempo.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Una scatola con 21 piccoli giochi diversi, ognuno spiegabile e giocabile in circa un minuto.",
    "tipologia_tecnico": "Varie (21 mini-giochi)",
    "componenti": "21 Carte Arcipelago · 4 Dischi neri · 4 Dischi bianchi · 1 Dado · 1 Sacchetto di stoffa · 60 Cubi in 6 colori (10 per colore: giallo, rosso, verde, blu, bianco, nero)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "aquatica",
    "titolo": "Aquatica",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Le vostre carte, giocate bene, si incastrano una nell'altra: in un turno fortunato potete arrivare a mettere in fila anche dieci azioni di seguito. Le vostre mante aiutano finché non si stancano — poi restano lì, inutili, finché non trovate il modo di farle riposare.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gestiscono carte e risorse sottomarine per fare le collezioni più ricche, come una raccolta di figurine.",
    "tipologia_tecnico": "Gestione carte · Gestione risorse · Raccolta set",
    "componenti": "1 Plancia di gioco · 4 Plance giocatore · 56 carte Territorio · 8 carte Re · 24 carte Personaggio Iniziale (4 set da 6) · 18 carte Personaggio dell'Oceano · 16 miniature Mante Addestrate (4 per giocatore) · 23 miniature Mante Selvagge · 5 Segnalini Obiettivo fronte-retro",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "azul-summer-pavillion",
    "titolo": "Azul Summer Pavillion",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Ogni turno cambia il colore jolly, e la tessera che sembrava inutile un attimo prima diventa improvvisamente quella che vi serviva. Le stelle del vostro pannello si riempiono con regole diverse l'una dall'altra: un mosaico che cresce a ogni round, quasi mai come lo avevate immaginato voi.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono tessere colorate da vassoi comuni e si compone un disegno geometrico sul proprio pannello, come un mosaico.",
    "tipologia_tecnico": "Drafting di tessere · Costruzione schema",
    "componenti": "Regolamento senza elenco componenti",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "bloom-town",
    "titolo": "Bloom Town",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Ogni turno scegliete una tessera e la incastrate nella vostra città. Sembra semplice, finché non vi accorgete che il pezzo perfetto per quel buco l'ha appena preso il vostro vicino — e che quel buco vi resterà lì, a guardarvi, fino alla fine della partita.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono tessere da un gruppo comune, come lo scambio di figurine, e si piazzano per costruire pezzo dopo pezzo la propria città.",
    "tipologia_tecnico": "Drafting di tessere · Piazzamento · Costruzione città",
    "componenti": "1 Plancia Piazza Cittadina · 4 Plance Città (a due facce) · 4 Gettoni Bonus · 1 Segnalino Primo Giocatore · 65 Tessere Edificio (13 per tipo: Uffici, Metro, Parchi, Case, Negozi) · 10 Tessere Comunità (2 per tipo) · 70 Gettoni Punti Sviluppo (valori 1/3/10/20)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "champions",
    "titolo": "Champions!",
    "giocatori": "3 - 5",
    "giocatori_min": 3,
    "giocatori_max": 5,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Otto concorrenti, veri o immaginari, si sfidano in duelli improbabili decisi dal voto di tutti i giocatori. Indovinare il vincitore conta più della logica: il pubblico ha sempre l'ultima parola.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Un gioco da fare in gruppo dove si vota chi vincerà ogni sfida, un po' come un piccolo torneo a indovinare, stile Indovina Chi — o come votare il proprio preferito in un talent show.",
    "tipologia_tecnico": "Party · Votazione · Deduzione",
    "componenti": "110 carte Duello · 8 plance · 16 carte Voto (8 di ogni colore) · 8 schede Personaggio · 8 pennarelli cancellabili · 8 tessere Partecipante · 1 regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "cocorido-all-arrembaggio",
    "titolo": "CocoRido All'Arrembaggio",
    "giocatori": "3 – 10",
    "giocatori_min": 3,
    "giocatori_max": 10,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Uno di voi legge una frase a metà, gli altri completano con la carta più assurda che hanno in mano — e chi ha letto decide, a modo suo, quale risposta gli ha strappato la risata più sincera. Chi vince quel turno diventa il prossimo a leggere.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Un gioco da fare in gruppo per ridere insieme, dove si gioca una carta tutti nello stesso momento.",
    "tipologia_tecnico": "Party · Gestione mano · Azione simultanea",
    "componenti": "Solo carte (numero non fornito)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "conspiracy",
    "titolo": "Conspiracy",
    "giocatori": "2 - 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Costruite una piramide di carte a rovescio, pescando fino a tre carte per volta e scegliendone solo una: le altre restano scoperte sul tavolo, pronte per essere prese dal prossimo giocatore. E la carta delle perle cambia proprietario ogni volta che qualcuno vi supera in quantità.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gestiscono le carte in mano e si finge di avere alleanze che non si hanno, come quando si bluffa giocando a carte.",
    "tipologia_tecnico": "Gestione mano · Bluff",
    "componenti": "60 carte Nobile (12 per ciascuna delle 5 Razze) · 24 carte Luogo · 20 gettoni Stemma (4 set in 5 colori) · 1 segnalino Maestro delle Perle · 1 carta Tracciato delle Perle · 1 segnalino Tracciato delle Perle",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "corinth",
    "titolo": "Corinth",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Si lanciano nove dadi insieme e si dispongono in fila dal valore più alto al più basso: prendete tutti i dadi di un livello e fate l'azione collegata. Più aspettate a scegliere, più dadi restano — e più forte è la tentazione di rimandare ancora un turno.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono dadi da un gruppo comune per costruire rotte commerciali, come quando si uniscono i puntini su una mappa.",
    "tipologia_tecnico": "Drafting di dadi · Costruzione rotte · Punteggio di area",
    "componenti": "1 blocco fogli Giocatore · 1 plancia Porto · 9 dadi bianchi · 3 dadi gialli · 1 regolamento · (regolamento in tedesco)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "draftosaurus",
    "titolo": "Draftosaurus",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "A ogni turno qualcuno lancia un dado che decide dove tutti gli altri devono piazzare il proprio dinosauro — tranne chi ha lanciato, che lo mette dove vuole. Un piccolo dispetto a turno, e il vostro zoo dei sogni si scontra ogni volta con la fortuna di chi tira.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si sceglie a turno un dinosauro da un sacchetto comune e lo si piazza nel proprio zoo.",
    "tipologia_tecnico": "Drafting · Piazzamento tessere",
    "componenti": "5 plance Zoo (lato estate e lato inverno) · 60 dinosauri (10 per 6 specie differenti) · 1 dado Piazzamento · 1 sacchetto di pesca",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "dungeonology",
    "titolo": "Dungeonology",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●●",
    "livello_label": "Prenditi la serata",
    "livello_key": "da-serata",
    "descrizione": "Non uccidete i mostri del dungeon: li osservate di nascosto e prendete appunti sulle loro abitudini, sperando che nessuno vi scopra. Gli altri studiosi stanno facendo lo stesso — e possono rovinarvi la tesi prima che la finiate, quindi la cattedra non è mai davvero al sicuro fino all'ultimo turno.",
    "descrizione_estesa": "A ogni turno stendete una nuova tessera per illuminare un pezzo di dungeon ancora al buio, e decidete se spingervi oltre o fermarvi a raccogliere quello che avete già scoperto: più andate a fondo, più informazioni potete portare a casa, ma cresce anche il rischio di far scattare l'allarme. I cubetti di conoscenza che raccogliete restano segreti fino alla fine — nessuno sa esattamente quanto avete capito voi, e questo rende ogni vostra mossa un piccolo bluff silenzioso. Gli altri studiosi non stanno a guardare: hanno le loro carte per rallentarvi o portarvi via il momento buono, e capita che la mossa preparata con cura salti perché qualcuno ha giocato la carta giusta un istante prima di voi. Si arriva all'ultimo turno senza sapere davvero chi vincerà, ed è quasi sempre quello il racconto che resta: la cattedra che sembrava già vostra, portata via all'ultima mossa da chi aveva taciuto meglio di voi.",
    "tipologia_chiaro": "Si esplora un dungeon muovendosi sulla mappa e gestendo le carte in mano, come una piccola spedizione da studiosi.",
    "tipologia_tecnico": "Esplorazione · Gestione mano · Movimento su mappa",
    "componenti": "4 Miniature Studenti · 1 Miniatura Boss Laetus · 1 Carta del Boss · 1 Plancia del Campus · 3 Carte Panico · 3 Carte Allerta · 3 Carte Clan · 1 Sacchetto dell'Università · Miniature Matricole (40 Normali + 5 Omega) · 64 Cubi Informazione · 19 Plance delle Zone · 105 Carte Trucchetto · 16 Mazzo Randomizzatore · 15 Carte Sfiga · 10 Carte Specializzando · 4 Bacheca · 4 Carte degli Studenti · 36 Segnalini",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "era-il-medioevo",
    "titolo": "Era Il Medioevo",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "I vostri dadi rappresentano contadini, preti, nobili e borghesi: li tirate e li usate per costruire, pezzo su pezzo, una vera città tridimensionale sul tavolo. Attenzione però: alcune combinazioni scatenano disastri che possono colpire gli avversari, o ritorcersi contro di voi.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi per ottenere materiali e si costruisce fisicamente il proprio villaggio con pezzi tridimensionali, come con i mattoncini.",
    "tipologia_tecnico": "Piazzamento dadi · Gestione risorse · Costruzione 3D",
    "componenti": "71 Edifici (8 Fortezze, 18 Capanne, 5 Palazzetti, 3 Municipi, 2 Cattedrali, 3 Monasteri, 5 Chiese, 16 Fattorie, 2 Università, 3 Segherie, 3 Ospedali, 3 Mercati) · 32 Mura (lunghezze varie da 2 a 6) · 27 Terre Bruciate · 36 Dadi (5 blu Cittadini, 5 bianchi Preti, 8 grigi Guerrieri, 18 gialli Contadini) · 25 Segnalini (6 per giocatore + 1 Primo Giocatore) · 5 Gettoni Tracciato · 4 Schermi · 4 Plance Giocatore · 1 Blocco Segnapunti",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "florenza-dice-game",
    "titolo": "Florenza Dice Game",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Chi tira i dadi ne sceglie tre per sé, e gli altri si dividono uno a testa quello che resta — un vantaggio evidente per chi tira, bilanciato dal fatto che il turno gira e tocca a tutti. Con quei dadi commissionate opere e costruite palazzi nella Firenze del Rinascimento.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi e si decide dove piazzare ciascuno, un po' come nello Yahtzee, ma per costruire palazzi e commissionare opere d'arte invece di fare punteggio.",
    "tipologia_tecnico": "Piazzamento dadi · Gestione risorse · Set collection",
    "componenti": "1 plancia Dadi · 1 blocco di fogli Rione (fronte)/tabella Edifici (retro) · 6 dadi in 6 colori (bianco, marrone, grigio, verde, rosso, giallo) · 4 matite · 1 regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "gasha",
    "titolo": "Gasha",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Girate la manovella della macchina e sperate che esca proprio il pezzo che vi manca per completare il set — ma non lo scoprite finché non l'avete già preso. Ogni estrazione è un piccolo salto nel buio, esattamente come i distributori a sorpresa a cui il gioco si ispira.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si può continuare a rischiare per un premio migliore, o fermarsi e tenere quello che si ha già, come con gli ovetti a sorpresa: non sai mai cosa esce finché non lo apri — lo stesso brivido delle loot box nei videogiochi, che di questi distributori sono in realtà le eredi dirette.",
    "tipologia_tecnico": "Spingi la sorte · Raccolta set",
    "componenti": "75 Carte Gasha (15 Ragazza Magica, 15 Kitsune, 15 Robot, 15 Rapa, 15 Sushi) · 35 Carte Premio · 15 Segnalini Bonus",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "hats",
    "titolo": "Hats",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Ogni turno scambiate un cappello con quelli sul tavolo, cercando di completare la vostra collezione — ma il cappello che vi piace di più conviene proteggerlo, perché vale doppio se resta con voi fino alla fine. Otto turni, tutti a rubarsi i colori a vicenda.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scambiano carte con gli altri per completare la propria collezione di cappelli, come una raccolta di figurine.",
    "tipologia_tecnico": "Gestione mano · Costruzione schema · Raccolta set",
    "componenti": "42 carte Cappello (7 colori) · 1 plancia Tavolino da Tè · 1 Tovagliolo punteggio · 1 pennarello cancellabile · 1 Biscotto (non commestibile)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "hippocrates",
    "titolo": "Hippocrates",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●●",
    "livello_label": "Prenditi la serata",
    "livello_key": "da-serata",
    "descrizione": "Ogni turno accogliete pazienti che avrebbero tutti bisogno di cure urgenti, ma potete curarne solo alcuni: scegliere chi lasciare in sala d'attesa vi costa reputazione. E se dimenticate di pagare i vostri dottori, se ne vanno — proprio quando servono di più.",
    "descrizione_estesa": "Il vero rompicapo arriva quando dovete assegnare davvero i vostri dottori ai pazienti: ogni malato ha bisogno di uno specialista di una regione precisa e di un tipo esatto di medicina — pozione, erba o unguento — e capita di avere in mano il dottore perfetto ma non la fiala che gli serve, o il contrario. Prima di arrivarci, però, dovete costruire la squadra: assumere nuovi dottori e comprare i kit giusti costa dracme, le stesse dracme che vi servono per pagare chi avete già assunto, quindi ogni round si gioca già in anticipo su quello successivo. Il gioco dura quattro round soltanto, e si sente: una scelta sbagliata all'inizio ha tutto il tempo di farsi sentire, ma non quello di essere corretta con calma. Alla fine non si guardano solo le dracme in cassa: un ospedale ricco ma con la reputazione a terra ha comunque perso qualcosa, ed è quel numero — non i soldi — quello che resta in mente uscendo dal tavolo.",
    "tipologia_chiaro": "Si mandano i propri dottori a occupare i posti disponibili prima degli altri — come essere i primi della fila — gestendo le scorte dell'ospedale.",
    "tipologia_tecnico": "Piazzamento lavoratori · Gestione risorse · Piazzamento tessere",
    "componenti": "1 Tabellone bifacciale · 6 dadi Welcome · 90 Fiale Medicina (30 Pozioni, 30 Erbe, 30 Unguenti) · 60 Monete Dracma (20 da valore 2, 40 da valore 1) · 12 gettoni Assistente (4 per ciascuno dei 3 tipi) · 30 Kit Medicina · 30 Tessere Conoscenza · 72 Pazienti (12 per ciascuna delle 6 regioni) · 30 Dottori (5 per ciascuna delle 6 regioni) · 4 Plance Giocatore · 4 Dottori Base · 4 Segnalini Welcome · 4 gettoni Opzione · 4 Segnalini Reputazione · 4 Segnalini Punti Vittoria · 4 gettoni 50/100+ PV (1 per colore) · (regolamento in inglese)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "kingdomino",
    "titolo": "Kingdomino",
    "giocatori": "2 - 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Costruite il vostro regno componendo tessere a domino di foreste, laghi e campi di grano. Le tessere con più corone valgono di più, ma vi costringono a scegliere per ultimi al turno successivo.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono tessere a domino da un gruppo comune e si compone, pezzo dopo pezzo, il proprio regno.",
    "tipologia_tecnico": "Drafting di tessere · Piazzamento · Costruzione regno",
    "componenti": "4 tessere Iniziali · 48 tessere Domino · 4 Castelli 3D (rosa, giallo, verde, blu) · 8 Re in legno (2 per colore) · 1 blocco Punteggio · 1 Torre 3D · (regolamento in tedesco)",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "lo-scatto-perfetto",
    "titolo": "Lo Scatto Perfetto",
    "giocatori": "2 - 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Sovrapponete carte bucate come fossero l'obiettivo della vostra macchina fotografica, cercando di inquadrare bene l'animale sotto. Chi inquadra lo Yeti nascosto tra le tessere si porta a casa un bonus che nessun altro può più prendere.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si piazzano carte per fotografare animali e si raccolgono le foto per tipo, come una raccolta di figurine.",
    "tipologia_tecnico": "Piazzamento carte · Raccolta set",
    "componenti": "1 plancia di gioco (con istruzioni montaggio) · 40 carte Paesaggio · 104 tessere Foto · 34 carte Album · 1 segnalino 1o giocatore · segnalini Scatto Perfetto · 1 regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "machi-koro",
    "titolo": "Machi Koro",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "A ogni turno lanciate i dadi, ma il numero che esce non paga solo voi: alcuni dei vostri edifici incassano anche quando tira l'avversario. Un classico immediato: si capisce in due minuti, e si sorride ogni volta che il dado sbagliato arricchisce l'altro invece di voi.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi e si comprano edifici che fanno guadagnare soldi ogni turno, un po' come in Monopoli — solo che qui ognuno costruisce la propria città per conto suo, senza girare sul tabellone.",
    "tipologia_tecnico": "Tiro di dadi · Costruzione motore · Gestione carte",
    "componenti": "108 carte totali: Carte Iniziali (Edifici Iniziali 2 tipi + Edifici Principali 4 tipi), Carte Riserva (Grandi Edifici 3 tipi + Edifici 12 tipi) · 60 monete (tagli 1/5/10) · 2 dadi · 1 Regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "meepleland",
    "titolo": "Meepleland",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Piazzate giostre e servizi cercando di non lasciare vicoli ciechi: un percorso chiuso per sbaglio significa visitatori bloccati e un'attrazione costosa che resta vuota fino alla fine. Il parco che vince è quello più facile da attraversare, non quello con più giostre.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si piazzano attrazioni sulla propria mappa e si tengono i conti dei soldi, un po' come costruire il proprio piccolo luna park.",
    "tipologia_tecnico": "Piazzamento tessere · Gestione risorse · Area management",
    "componenti": "4 plance individuali Spazi · 1 plancia Parcheggio · 4 tessere ampliamento Spazi · 4 tessere Ingressi Parco supplementari · 101 tessere Attrazione/Servizi (32 piccole con pubblicità sul retro, 40 medie, 29 grandi) · 17 tessere bus · 124 segnalini Visitatore (35 verdi, 35 blu, 30 rosa, 24 gialli) · 1 gettone Biglietti del parco (1o giocatore) · 1 indicatore di manche · 52 tagli di denaro (33 da 1$ e 19 da 5$) · 4 Ingressi giocatore (2 Colonne + Insegna per giocatore) · 1 blocchetto segnapunti",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "meeples-and-monsters",
    "titolo": "Meeples and Monsters",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Pescate a caso dal vostro sacchetto: quello che esce decide cosa potete fare in quel turno, contadini compresi, che spesso non servono a molto. Con il tempo li fate diventare cavalieri, chierici o maghi — ma il sacchetto resta pieno di sorprese fino all'ultima partita.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si esplora un dungeon mandando i propri eroi a occupare i posti disponibili prima degli altri — come essere i primi della fila — e si combatte contro i mostri.",
    "tipologia_tecnico": "Esplorazione dungeon · Piazzamento lavoratori · Combattimento",
    "componenti": "Meeple base: 48 bianchi (Contadini), 15 neri (Cavalieri), 18 blu (Guerrieri), 18 gialli (Maghi), 18 rossi (Chierici), 20 grigi (Corruzione) · Meeple Prestigio: 5 verdi (Ranger), 5 viola (Paladini), 5 arancioni (Sciamani) · 2 segnalini Primo Giocatore · 12 segnalini Giocatore (3 per colore) · 4 sacchetti di stoffa · 1 plancia Città · 4 plance Giocatore · 1 tabellone Scontro Finale · 15 tessere Luogo · 16 carte Eroe Base bifacciali · 12 carte Eroe Prestigio · 47 carte Mostro (12 liv.1, 20 liv.2, 8 liv.3, 4 Consiglio Oscuro [3 Signori + 1 Scagnozzo], 3 carte Arriva il Consiglio Oscuro) · 6 gettoni Bonus Consiglio Oscuro · 44 carte Missione · (regolamento in inglese)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "mindup",
    "titolo": "MindUp!",
    "giocatori": "3 - 6",
    "giocatori_min": 3,
    "giocatori_max": 6,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Ogni turno tutti giocano una carta in segreto, poi si scoprono insieme: si forma una fila ordinata dal basso all'alto e ognuno prende la carta della fila precedente nella stessa posizione della propria. Sembra un dettaglio da niente, finché non vi accorgete che la posizione conta più della carta stessa.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Tutti giocano una carta nello stesso momento, non a turni, come nella morra cinese (sasso-carta-forbici) — o come le mini-sfide simultanee di certi party game ai videogiochi (tipo Mario Party).",
    "tipologia_tecnico": "Azione simultanea · Gestione mano",
    "componenti": "Ancora incellofanato: componenti da contare a mano al ritiro",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "momiji",
    "titolo": "Momiji",
    "giocatori": "1 - 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Nel Giardino Imperiale raccogliete e giocate carte foglia per completare collezioni e conquistare le ghiande più preziose. Chi cattura lo scoiattolo guadagna un piccolo vantaggio a ogni turno degli altri.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gestiscono le carte in mano e se ne scelgono altre da un gruppo comune, per fare le collezioni di foglie più ricche, come una raccolta di figurine.",
    "tipologia_tecnico": "Gestione mano · Drafting · Raccolta set",
    "componenti": "84 carte Foglia (6 tipi x 14) · 16 gettoni Obiettivo · 12 Foglie Dorate · 1 meeple Scoiattolo · 34 tessere Paesaggio · 42 gettoni Ghianda (12 da valore 5 + 30 da valore 1) · 1 blocco segnapunti · (regolamento in inglese)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "new-york-zoo",
    "titolo": "New York Zoo",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Incastrate pezzi di forme diverse per costruire i recinti del vostro zoo, sperando che il conto torni prima che finisca lo spazio sulla plancia. Gli animali dentro si riproducono da soli, e un recinto pieno si smonta di colpo lasciando spazio per un'attrazione nuova — un piccolo Tetris che cambia continuamente sotto i vostri occhi.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si incastrano pezzi di forme diverse, come nel Tetris, scegliendoli a turno da un gruppo comune.",
    "tipologia_tecnico": "Piazzamento poliomini · Drafting di tessere",
    "componenti": "TESSERE ATTRAZIONE (puzzle): 16 da 1 spazio, 6 da 2, 6 da 3, 2 da 4, 1 da 6, 1 da 8 · TESSERE RECINTO (puzzle): 8 verde chiarissimo (4 spazi), 15 verde chiaro (5), 15 verde scuro (6), 7 verde scurissimo (7) · 8 plance zoo bifacciali · 1 striscia azioni · PEDINE ANIMALE: 28 suricati, 26 fenicotteri, 24 canguri arboricoli, 24 pinguini, 24 volpi artiche, 1 elefante · 2 tessere animale da 3 per ogni tipologia · 1 gettone Prova bianco · 5 segnalini azzurri movimento (solitario)",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "nobinobi-gdr-magia",
    "titolo": "NobiNobi GDR Magia",
    "giocatori": "1 – 5",
    "giocatori_min": 1,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Stessa struttura di Spada — i ruoli di narratore e protagonista girano a ogni turno — ma qui le prove si superano con incantesimi invece che con la spada, e i segreti da scoprire hanno il sapore della magia.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si inventa una storia insieme, come quando da bambini si giocava a \"facciamo finta che\", aiutandosi con carte e dadi.",
    "tipologia_tecnico": "Narrativo · Gioco di ruolo · Tiro di dadi",
    "componenti": "8 carte Personaggio · 20 Carte Luce · 20 Carte Ombra · 8 carte Introduzione · 40 carte Scena · 8 carte Epilogo · 1 Carta Master · 1 Carta Protagonista · 1 Carta riferimento · 2 carte Oggetti/Nemici · 6 dadi a 6 facce · 1 Regolamento",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "nobinobi-gdr-spada",
    "titolo": "NobiNobi GDR Spada",
    "giocatori": "1 – 5",
    "giocatori_min": 1,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "A ogni turno uno di voi pesca una carta scena e la racconta come Master, un altro la vive come protagonista tirando i dadi per superarla — poi i ruoli girano, e tocca a un altro inventare il pezzo successivo. Nessuno resta sempre a comandare, e la storia cambia direzione a ogni mano.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si inventa una storia insieme, come quando da bambini si giocava a \"facciamo finta che\", aiutandosi con carte e dadi.",
    "tipologia_tecnico": "Narrativo · Gioco di ruolo · Tiro di dadi",
    "componenti": "8 carte Personaggio · 20 Carte Luce · 20 Carte Ombra · 8 carte Introduzione · 40 carte Scena · 8 carte Epilogo · 1 Carta Master · 1 Carta Protagonista · 1 Carta riferimento · 2 carte Oggetti/Nemici · 6 dadi a 6 facce · 1 Regolamento",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "oddville",
    "titolo": "Oddville",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Avete solo quattro carte lavoratore, e ognuna fa una cosa diversa: quando le avete usate tutte, per riprenderle dovete pagare o aspettare il turno giusto. Ogni edificio conviene collegarlo con una strada a quelli già in città — la connessione vale più dell'edificio in sé.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono carte da un gruppo comune per costruire, edificio dopo edificio, una città bizzarra.",
    "tipologia_tecnico": "Drafting di carte · Costruzione città · Gestione risorse",
    "componenti": "64 carte Moneta/Edificio · 1 carta Piazza Principale · 16 carte Lavoratore (4 colori giocatore) · 36 lavoratori (4 colori) · 1 plancia Risorse · 12 carte Personaggio (4 simboli Gilda) · 1 Regolamento · (regolamento in inglese)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "once-upon-a-castle",
    "titolo": "Once Upon a Castle",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "A ogni turno chi lancia i dadi sceglie per primo cosa prendere, e gli altri si dividono quello che resta. Ognuno disegna il proprio castello su un foglio personale, in gara silenziosa per vedere chi lo finisce meglio.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi e si disegna il proprio castello sul foglio, ognuno per sé: gara a chi lo fa più bello.",
    "tipologia_tecnico": "Tiro di dadi · Disegno su foglio (roll-and-write) · Competitivo",
    "componenti": "1 blocco da disegno castello (fronte/retro) · 4 set di 10 gettoni colorati · 4 plance individuali (fronte/retro) · 2 dadi · 36 carte Invitati (16 Piccoli Costruttori + 20 Grandi Architetti)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "orbis",
    "titolo": "Orbis",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Ogni tessera di territorio che prendete lascia dietro di sé fedeli dello stesso colore su quelle vicine, rendendole più preziose per chi gioca dopo di voi. Quindi ogni vostra scelta regala qualcosa all'avversario, che lo vogliate o no.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono e si piazzano tessere di territorio, come lo scambio di figurine, gestendo i propri seguaci come una piccola scorta da amministrare.",
    "tipologia_tecnico": "Drafting di tessere · Piazzamento · Gestione risorse",
    "componenti": "10 tessere Divinità · 65 tessere Regione (20 liv.1, 20 liv.2, 25 liv.3) · 100 Adoratori (20 per ciascuno dei 5 colori) · 18 segnalini Annullamento · 5 segnalini Riduzione (1 per colore) · 5 segnalini Tempio · 1 Regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "pandemic-reazione-rapida",
    "titolo": "Pandemic Reazione Rapida",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Una clessidra di due minuti scandisce ogni round: dovete lanciare e rilanciare i dadi in fretta e decidere insieme chi vola dove. Se la sabbia finisce prima che abbiate deciso, perdete tempo prezioso e arriva un'altra città in crisi — non c'è un attimo per pensarci su.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gioca tutti insieme contro il gioco, con la clessidra che corre, un po' come nel gioco di carta e penna 'Città, Fiumi, Monti' quando il tempo sta per scadere.",
    "tipologia_tecnico": "Cooperativo · Tempo reale · Gestione mano",
    "componenti": "24 Dadi (6 per ciascuno dei 4 colori) · 4 Pedine Giocatore (1 per colore) · 20 Casse di Scorte (4 per ciascuno dei 5 colori) · 1 Segnalino Aereo con piedistallo · 24 Carte Città · 7 Carte Ruolo · 4 Carte di Consultazione · 15 Carte Crisi · 1 Tabellone dell'Aereo · 1 Clessidra (2 minuti) · 9 Segnalini Tempo · 1 Segnalino Scorie",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "railroad-ink-blu",
    "titolo": "Railroad Ink Blu",
    "giocatori": "1 – 6",
    "giocatori_min": 1,
    "giocatori_max": 6,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Stessa idea di Railroad Ink Rosso: dadi in comune, disegno personale, foglio suo per ciascuno. Qui però a complicarvi la mappa non sono lava e meteore, ma fiumi e laghi da aggirare con le vostre strade.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi e ognuno disegna sul proprio foglio, cercando di collegare le strade come quando si uniscono i puntini.",
    "tipologia_tecnico": "Tira e scrivi · Costruzione rete",
    "componenti": "6 plance · 4 dadi Percorso · 2 dadi Fiume · 2 dadi Lago · 6 pennarelli · (Deep Blue Edition)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "railroad-ink-rosso",
    "titolo": "Railroad Ink Rosso",
    "giocatori": "1 – 6",
    "giocatori_min": 1,
    "giocatori_max": 6,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Si lanciano i dadi e tutti, nello stesso momento, disegnano strade e ferrovie sul proprio foglio: stessi dadi per tutti, ma ogni mappa finisce diversa. Le strade che restano a metà, senza uscire dal foglio, vi tolgono punti — e con i dadi Lava e Meteora anche un pezzo di mappa può esplodervi in faccia.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si lanciano i dadi e ognuno disegna sul proprio foglio, cercando di collegare le strade come quando si uniscono i puntini.",
    "tipologia_tecnico": "Tira e scrivi · Costruzione rete",
    "componenti": "6 plance · 4 dadi Percorso · 2 dadi Lava · 2 dadi Meteora · 6 pennarelli · (Blazing Red Edition)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "rune-stones",
    "titolo": "Rune Stones",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Ogni volta che giocate due carte insieme, quella con il numero più alto sparisce per sempre dal vostro mazzo: dovete decidere se sacrificare una carta forte per liberarvi delle deboli, o il contrario. Con gemme e artefatti forgiate pietre runiche che vi danno un potere diverso da quello di tutti gli altri stregoni al tavolo.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono carte da un gruppo comune e si costruisce nel tempo una combinazione che produce sempre più risorse, come una catena di montaggio che cresce.",
    "tipologia_tecnico": "Drafting di carte · Costruzione motore · Raccolta set",
    "componenti": "1 Tabellone · 68 carte Creatura · 8 carte Drago bianche (num. 71-78) · 60 carte in blu/giallo/verde/rosso (num. 11-70) · 28 Artefatti (7 per colore) · 8 Artefatti Jolly · 20 pezzi Minerale · 24 Rune · 24 gettoni Azione (3 per ciascuno di 8 tipi) · 60 Gemme (15 per colore) · 15 Gemme Jolly bianche · 1 segnalino Primo Giocatore · 1 dado · 1 Trono · 1 regolamento · Per ogni giocatore (4 colori): 1 Plancia, 1 carta riassuntiva, 8 carte Druido (num. 100-107), 1 segnalino punteggio · (regolamento in inglese)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "santiago-de-cuba",
    "titolo": "Santiago De Cuba",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Un'unica auto gira in senso orario lungo la via, e voi decidete quanto farla avanzare: il primo passo è gratis, ogni passo in più vi costa un peso. Fermarvi davanti al cubano giusto vi frutta merci o denaro — e se qualcuno usa un edificio che avete costruito voi, il punto va comunque a voi.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si muove una pedina su una ruota di azioni per commerciare merci e costruire rotte, come le lancette di un orologio che indicano cosa si può fare in quel momento.",
    "tipologia_tecnico": "Rondello · Costruzione rotte · Gestione risorse",
    "componenti": "1 Tabellone · 4 Schermi · 12 Pezzi Edificio · 9 Pezzi Cittadino · 4 Pedine · 12 Gettoni Proprietà (3 per colore) · 5 Dadi speciali a 6 facce · 48 Merci (8 per ciascuna: canna da zucchero, agrumi, tabacco, rum, sigari + 8 legno) · 60 gettoni Punti Vittoria (valori 1/2/3/5/10) · 36 Monete (pesos) · 1 Auto · 1 Nave · 1 Contatore valore merci · (regolamento in spagnolo)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "snow-time",
    "titolo": "Snow Time",
    "giocatori": "3 - 5",
    "giocatori_min": 3,
    "giocatori_max": 5,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Arrampicatevi sull'albero magico per rubare i frutti prima dei rivali, ramo dopo ramo. Chi resta solo li raccoglie tutti, ma un'imboscata dall'alto può rovinarvi la festa.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Tutti scelgono la propria mossa nello stesso momento, senza sapere cosa faranno gli altri, un po' come alla morra cinese — o come le mini-sfide simultanee di party game da console (tipo Mario Party).",
    "tipologia_tecnico": "Azione simultanea · Bluff · Dadi",
    "componenti": "1 Tabellone · 2 Dadi · 15 Segnalini Frutto · 5 Pedine in legno · 50 Carte (per ciascun colore: 1 Pedina + 7 Carte Personaggio num. 1-7 + 3 Carte Speciali: Guaritore, Osservatore, Bufera)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "sobek-2-giocatori",
    "titolo": "Sobek 2 giocatori",
    "giocatori": "2",
    "giocatori_min": 2,
    "giocatori_max": 2,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Un'ankh sul tabellone punta in due direzioni: potete prendere gratis la tessera più vicina, oppure allungarvi per quella che vi serve davvero — ma ogni tessera che scavalcate diventa corruzione, e la corruzione alla fine si paga cara.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono tessere di merce dal mercato comune per fare le collezioni più ricche, come una raccolta di figurine.",
    "tipologia_tecnico": "Drafting di tessere · Raccolta set",
    "componenti": "1 plancia Mercato · 13 gettoni Piroga · 1 sacchetto Deben + 13 gettoni Deben · 1 Ankh · 2 schede Aiuto Giocatore · 10 tessere Iniziali (retro grigio) · 45 tessere Merce (retro nero) · 10 tessere Personaggio (retro rosso) · 2 plance Corruzione · 2 gettoni Punteggio",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "sock-monsters",
    "titolo": "Sock Monsters",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Muovete di nascosto il vostro mostro sollevando la pedina: solo dopo scoprite se si è addormentato a metà strada, oppure può ancora rubare un calzino. Poi tocca all'elfo cercare le coppie nascoste tra cassetti e armadietti, prima che i mostri gliele portino via.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Un gioco di memoria, come il classico Memory, dove ci si muove su una griglia di stanze.",
    "tipologia_tecnico": "Memoria · Movimento su griglia",
    "componenti": "1 scacchiera 3D · 36 tessere parquet (quadrate) · 16 segnalini ricerca (rotondi) · 4 schede elfo · 40 calzini (8 per ciascuno dei 5 colori) · 1 sacchetto · 4 pedine elfo · 4 mostrini in plastica · 1 dado mostro · 1 foglio adesivi · 1 manualetto regole · 1 manualetto varianti · 1 inserto casa con 4 stanze chiuse",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "spirit-of-the-forest",
    "titolo": "Spirit of the Forest",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Raccogliete tessere spirito legate ai quattro elementi della foresta, sfidandovi a costruire la collezione più ricca prima che il tavolo resti vuoto. Sullo scaffale accanto trovi anche Moonlight: la stessa foresta di notte, che unita alla scatola base trasforma la sfida in un'alleanza contro il buio (o in una partita in solitaria, se preferisci).",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono tessere spirito da un gruppo comune per fare le collezioni più ricche, come una raccolta di figurine.",
    "tipologia_tecnico": "Piazzamento tessere · Punteggio di area · Competitivo (con modulo cooperativo Moonlight incluso nella scatola)",
    "componenti": "BASE: 48 Tessere Spirito, 14 Segnalini Favore, 12 Gemme, 1 Carta Eremita · ESPANSIONE MOONLIGHT: 8 Moonlight bits, 2 Nocturnal Creatures (1 Shadow + 1 Light), 14 Moonlight tiles, 4 Eclipse tokens, 1 Moonlight scorepad, 15 Enchantment cards, 1 Competitive player aid card, 8 Moonlight cards, 8 Objective cards · (include espansione Moonlight, in inglese)",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": "Sono due scatole distinte: Spirit of the Forest (base, competitivo, si gioca da sé) e Spirit of the Forest: Moonlight (l'espansione notturna). Moonlight richiede sempre la scatola base per essere giocata — non funziona da sola sullo scaffale. Chi cerca il cooperativo (o la variante in solitario) prende entrambe le scatole insieme."
  },
  {
    "slug": "tang-garden",
    "titolo": "Tang Garden",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●●",
    "livello_label": "Prenditi la serata",
    "livello_key": "da-serata",
    "descrizione": "Ogni tessera che piazzate deve incrociare esattamente i bordi di quella già sul tavolo — un incastro che si complica partita dopo partita. E i personaggi che mettete nel giardino fanno punti solo se, guardando dritti davanti a sé, vedono proprio quello che desiderano: sbagliate la prospettiva, e quel posto vale zero.",
    "descrizione_estesa": "Ogni turno la scelta è secca — piazzare una tessera di terreno o giocare una carta decorazione — ma dietro quella scelta minima c'è più di quanto sembri: un fiore di loto vive solo sull'acqua, un albero solo sulla terra, e trovare il punto giusto nel giardino che state costruendo insieme agli altri diventa un piccolo rompicapo a ogni mano. Avete anche quattro lanterne che vi concedono un'azione in più — una seconda tessera, una seconda decorazione, spostare un personaggio all'ultimo momento — ma una volta usate si spengono, e per riaccenderle dovete scartare tre tessere di paesaggio dello stesso tipo: va deciso se tenerle di scorta per il momento giusto o consumarle subito. Il giardino cresce lentamente sotto gli occhi di tutti, in un'atmosfera che chi lo ha provato descrive come meditativa più che competitiva — poi arriva il turno in cui un personaggio piazzato a inizio partita guarda finalmente nella direzione giusta, e quello che sembrava solo un dettaglio decorativo si trasforma in un pugno di monete.",
    "tipologia_chiaro": "Si compone un giardino piazzando tessere e si fanno gruppi di decorazioni uguali, come una raccolta di figurine; più le zone create sono grandi, più valgono.",
    "tipologia_tecnico": "Piazzamento tessere · Punteggio di area · Raccolta set",
    "componenti": "1 regolamento · 1 plancia Giardino · 1 tessera iniziale (fronte/retro) · 60 tessere Giardino · 54 carte Decorazione · 60 monete · 16 tessere Lanterna · 4 tessere Lanterna Solo · 4 plance Giocatore · 12 carte Personaggio · 12 figure Personaggio · 8 grandi tessere Paesaggio · 12 piccole tessere Paesaggio · 8 grandi gettoni Paesaggio · 8 piccoli gettoni Paesaggio · 36 decorazioni · 12 cubi · 4 gettoni Personaggio · 1 gettone Ingegnere (primo giocatore) · (regolamento in francese)",
    "tags": [
      "bello-da-vedere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "the-hunger",
    "titolo": "The Hunger",
    "giocatori": "2 – 6",
    "giocatori_min": 2,
    "giocatori_max": 6,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Siete vampiri in corsa contro l'alba: ogni preda catturata rallenta il vostro mazzo di carte, quindi più cacciate più rischiate di restare fuori quando sorge il sole. Chi è troppo goloso perde tutto.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono carte da un gruppo comune e si decide, turno dopo turno, se continuare a rischiare o fermarsi e tenere quello che si ha.",
    "tipologia_tecnico": "Drafting di carte · Gestione mano · Spingi la sorte",
    "componenti": "122 carte Caccia (80 Umani, 22 Famigli, 20 Poteri) · 6 schede Vampiro · 6 mazzi Iniziali da 6 carte (1 per Vampiro) · 6 segnalini Vampiro in legno · 50 tessere Missione · 1 segnalino Luna · 3 carte Rosa · 1 Tabellone · 5 segnalini Castello · 26 segnalini Bonus · 1 Tracciato Caccia/Castello (da assemblare in base ai giocatori)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "villagers",
    "titolo": "Villagers",
    "giocatori": "1 – 5",
    "giocatori_min": 1,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Ogni carta che pescate può servire a voi, o solo a impedire che serva a chi gioca dopo — a volte conviene prenderla proprio per fare dispetto. Le catene di paesani dello stesso mestiere valgono sempre di più: un fabbro in più nella fila giusta cambia la partita.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono carte da un gruppo comune e si costruisce davanti a sé una fila di paesani che si aiutano a vicenda, come una catena di montaggio che cresce.",
    "tipologia_tecnico": "Drafting di carte · Costruzione motore · Tableau building",
    "componenti": "5 Carte Piazza del Villaggio · 5 Carte Riepilogo · 5 Fondatori · 6 Paesani della Strada Iniziale · 30 Paesani Base (Tagliaerba, Minatori, Mietitori) · 94 Carte Paesano · 2 Carte Mercato · 150 Segnalini Moneta in vari tagli · Carta Primo Giocatore · Carta Fine Fase Acquisizione · SOLITARIO: 24 Carte Evento + Carta Contessa + Carta Giullare",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "visconti-del-regno-occidentale",
    "titolo": "Visconti del Regno Occidentale",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●●",
    "livello_label": "Prenditi la serata",
    "livello_key": "da-serata",
    "descrizione": "Ogni carta che giocate decide anche quanto lontano si sposta il vostro Visconte sul tabellone — un doppio calcolo da soppesare a ogni turno, tra la mano e la mappa. Il regno può scivolare in povertà o esplodere di prosperità, e chi ha costruito meglio in quel momento preciso porta a casa la partita.",
    "descrizione_estesa": "Le tre carte che avete in mano si spostano ogni turno di una posizione, e quella che cade dal bordo della fila — la più vecchia, quella che avete tenuto troppo a lungo — si attiva da sola prima di sparire per sempre, nel bene o nel male. Con quello che guadagnate potete assumere un nuovo cittadino nella vostra fila di aiutanti, rendendola più forte per i turni a venire, ma ogni assunzione toglie risorse a qualcos'altro che vorreste fare. Sul tabellone personale avanzano due segnalini, uno di corruzione e uno di reputazione: quando si incrociano succede qualcosa — monete, un debito da scontare, un atto di buona fede che vale il doppio se lo tenete nascosto fino alla fine — e non sempre siete voi a decidere quando accade. Le partite si ricordano per il turno in cui tutto si incastra da solo: un'azione ne sblocca un'altra, gli aiutanti messi in fila nei turni precedenti arrivano tutti insieme al castello, e quel colpo da solo vale più di una manciata di turni giocati con calcolo.",
    "tipologia_chiaro": "Si mandano i propri aiutanti a occupare i posti disponibili prima degli altri — come essere i primi della fila — allargando la propria influenza sulla mappa.",
    "tipologia_tecnico": "Piazzamento lavoratori · Gestione mano · Influenza di area",
    "componenti": "72 Risorse (24 Calamai, 24 Ori, 24 Pietre) · 35 Manoscritti · 1 Castello · 1 Segnalino Primo Giocatore · 4 Plance Giocatore · 5 Sezioni di Tabellone · 4 Segnalini Corruzione · 4 Segnalini Reputazione · 50 Monete · 80 Lavoratori (20 per colore) · 4 Visconti (1 per colore) · 12 Sedi Corporazioni (3 per colore) · 12 Empori (3 per colore) · 12 Officine (3 per colore) · 16 Carte Giocatore · 4 Carte Bonus Sacerdote · 32 Carte Cittadino Iniziale · 10 Carte Cittadino Eroe · 68 Carte Cittadino Neutrale · 1 Carta Signore del Castello · 1 Carta Prosperità · 1 Carta Povertà · 30 Carte Contratto · 30 Carte Debito · 4 Carte Moltiplicatore · 1 Carta Riassuntiva (solitario) · 8 Carte Intrigo Iniziale (solitario) · 8 Carte Intrigo Futuro (solitario)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "watergate",
    "titolo": "Watergate",
    "giocatori": "2",
    "giocatori_min": 2,
    "giocatori_max": 2,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Uno di voi è Nixon e deve solo arrivare in fondo senza farsi inchiodare. L'altro è il Washington Post e deve collegare due prove al presidente prima che scada il tempo. Si gioca in due, su un tavolo piccolo, e si suda.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Un duello di carte in cui i due giocatori hanno ruoli e regole diverse tra loro, come nel gioco del gatto e del topo — o come nei videogiochi multigiocatore asimmetrici, dove uno caccia e gli altri si nascondono — per collegare o rompere una rete di prove.",
    "tipologia_tecnico": "Gioco di carte · Asimmetrico · Costruzione rete",
    "componenti": "1 Tabellone · 1 carta Consenso Amministrazione Nixon · 1 carta Consenso Editore · 20 carte Amministrazione Nixon · 20 carte Editore · 1 carta Iniziativa · 1 carta Riepilogo fine round · 9 segnalini Consenso · 1 segnalino Iniziativa · 36 tessere Prova · 7 tessere Foto · 1 sacchetto",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "welcome-to-new-las-vegas",
    "titolo": "Welcome to New Las Vegas",
    "giocatori": "1 – 100",
    "giocatori_min": 1,
    "giocatori_max": 100,
    "livello_dots": "●●○○",
    "livello_label": "Leggi e gioca",
    "livello_key": "da-soli",
    "descrizione": "Ogni turno si girano tre carte e si formano tre abbinamenti numero più effetto: ognuno sceglie in silenzio quello che gli serve e lo scrive sul proprio foglio. Si può giocare tutti insieme, letteralmente tutti — funziona anche in cento persone nella stessa stanza.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si girano carte al posto di lanciare i dadi, e ognuno segna sul proprio foglio quello che gli serve — un po' come alla Tombola, ma con le carte al posto dei numeri estratti.",
    "tipologia_tecnico": "Gira e scrivi · Raccolta set · Costruzione schemi",
    "componenti": "1 Blocco segnapunti (fronte città / retro punteggio) · 81 carte Casinò (16 Inaugurazione, 16 Costruzione, 16 Limousine, 17 Spettacolo, 16 Miglioramento) · 21 carte Progetto · 8 carte Solitario (3 Progetto Approvato + 5 Architetto ACME)",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "wild-space",
    "titolo": "Wild Space",
    "giocatori": "2 – 5",
    "giocatori_min": 2,
    "giocatori_max": 5,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Ogni carta equipaggio che giocate può innescarne un'altra già in tavola, se le condizioni tornano giuste. Costruire la combinazione al momento giusto scatena una reazione a catena che, in dieci turni, può ribaltare la partita.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si scelgono carte da un gruppo comune per costruire, turno dopo turno, un equipaggio sempre più forte, come una catena di montaggio che cresce.",
    "tipologia_tecnico": "Drafting di carte · Gestione mano · Costruzione motore",
    "componenti": "108 carte Equipaggio (60 Specialisti, 24 Emissari, 18 Robot, 6 Capitani) · 10 tessere Pianeta · 25 segnalini Nave Spaziale (5 per giocatore) · 5 segnalini Veterano (1 per giocatore) · 1 Blocchetto Segnapunti · 12 carte Pianeta Ostile (solitario) · 1 Regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "woodcraft",
    "titolo": "Woodcraft",
    "giocatori": "1 – 4",
    "giocatori_min": 1,
    "giocatori_max": 4,
    "livello_dots": "●●●●",
    "livello_label": "Prenditi la serata",
    "livello_key": "da-serata",
    "descrizione": "I vostri pezzi di legno sono dadi: li segate in due, li incollate insieme, li scartate se serve — e ogni taglio sbagliato è legno perso per sempre. Le azioni che nessuno sceglie diventano via via più convenienti, quindi anche aspettare, in questo gioco, è una mossa vera.",
    "descrizione_estesa": "Il vostro banco da lavoro è pieno di dadi di tre colori di legno diversi, e ogni ordine da consegnare chiede una combinazione precisa — magari due dadi verdi e uno marrone di un certo valore — che dovete costruire segando, incollando o facendo crescere quello che avete già in mano. Il problema è che gli ordini sul tavolo cambiano ogni turno, e càpita spesso di avere in mano il pezzo perfetto ma nessun cliente disposto a comprarlo in quel momento: allora lo si mette da parte, sperando che l'ordine giusto arrivi prima che qualcun altro se lo prenda. Con qualche partita si impara a mettere in fila piccoli passaggi che si alimentano da soli — un taglio che produce scarto, lo scarto che diventa colla, la colla che sblocca il pezzo successivo — e il momento in cui quella catena parte per la prima volta da sola è quello che si ricorda meglio. Fino ad allora, però, si passano diversi turni a fissare il proprio banco chiedendosi perché il legno che serve non è mai quello che si ha davanti.",
    "tipologia_chiaro": "Si aggiustano i dadi lanciati per ottenere il risultato che serve, e si mandano i propri artigiani a occupare i posti disponibili prima degli altri — come essere i primi della fila.",
    "tipologia_tecnico": "Manipolazione dadi · Gestione risorse · Piazzamento lavoratori",
    "componenti": "1 plancia ruota principale · 4 plance giocatori · 1 tabellone segnapunti · 1 foglio aiuto effetti autori · 7 tessere azione · 8 tessere vaso · 12 tessere assemblaggio · 4 tessere incollaggio · 9 segnalini riutilizzo-tessera · 3 tessere tracciato reputazione · 12 tessere sega · 1 tessera ad arco · 1 carta primo giocatore · 55 segnalini attrezzo · 20 segnalini scarti di legno · 16 segnalini lama della sega · 16 segnalini colla · 16 segnalini lanterna · 1 indicatore del Round · 8 indicatori + 8 segnapunti per ciascuno dei 4 colori · 14 dadi per ciascuno dei 3 colori (verde, giallo, marrone) · segnalini mirtillo di vario valore (3/5/10) · 32 carte ordine inizio partita · 32 carte ordine partita inoltrata · 27 carte aiuto inizio partita · 22 carte aiuto partita inoltrata · 8 carte ordine nocciola · 8 carte contratti pubblici · 10 carte per il solitario · 1 regolamento",
    "tags": [],
    "nota_due_scatole": ""
  },
  {
    "slug": "yokai",
    "titolo": "Yokai",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Non potete parlarvi. Nemmeno un cenno, nemmeno un'occhiata d'intesa. Dovete rimettere in ordine gli spiriti per colore aiutandovi solo con dei suggerimenti muti — e scoprirete che mettersi d'accordo in silenzio è molto più difficile, e molto più divertente, di quanto sembri.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gioca tutti insieme per vincere o perdere insieme, ma senza poter parlare: ci si deve capire con gli sguardi, come nel mimo.",
    "tipologia_tecnico": "Cooperativo · Comunicazione limitata · Gestione carte",
    "componenti": "16 Carte Yokai · 14 Carte Suggerimento · 6 Carte Affinità · 3 Carte Obiettivo",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "zefiria",
    "titolo": "Zefiria",
    "giocatori": "2 – 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●●●○",
    "livello_label": "Meglio farselo spiegare",
    "livello_key": "con-guida",
    "descrizione": "Siete Spiriti del Vento alle prese con un cielo in disordine: rimettete le venticinque isole sospese in fila, dalla più piccola alla più grande, prima che il tempo scada. Le tempeste vi rimescolano le carte per davvero, e ogni Spirito ha poteri diversi per uscirne insieme.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si collabora per rimettere in ordine le isole numerate prima che il tempo scada, un po' come riordinare in fila le carte di un mazzo numerato che qualcuno ha mischiato.",
    "tipologia_tecnico": "Cooperativo · Puzzle logico · Contro il tempo",
    "componenti": "5 carte Spirito del Vento · 5 pedine Spirito del Vento · 7 carte Tempesta · 25 carte Isola · 6 carte Griglia · 13 Gemme di Zefiria (6 rosse, 7 viola) · 4 carte Mappa di Zefiria · 1 carta Tracciato del Tempo (fronte/retro)",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  },
  {
    "slug": "zombie-kidz-evolution",
    "titolo": "Zombie Kidz Evolution",
    "giocatori": "2 - 4",
    "giocatori_min": 2,
    "giocatori_max": 4,
    "livello_dots": "●○○○",
    "livello_label": "Apri e gioca",
    "livello_key": "al-volo",
    "descrizione": "Difendete la scuola dall'invasione zombie chiudendo le quattro porte prima che i mostri dilaghino tra le aule. Ogni missione superata apre una busta sigillata: il gioco cresce e cambia, partita dopo partita.",
    "descrizione_estesa": "",
    "tipologia_chiaro": "Si gioca tutti insieme contro gli zombie, e il gioco stesso cambia e si trasforma partita dopo partita, come un album di figurine che si riempie col tempo — o, per chi preferisce, come un videogioco che salva i progressi e sblocca cose nuove a ogni partita.",
    "tipologia_tecnico": "Cooperativo · Legacy · Tiro di dadi",
    "componenti": "1 plancia · 4 tessere eroi · 1 dado zombi · 4 gettoni lucchetti · 8 supporti in plastica · 8 tessere zombi · 13 buste Evolution (sigillate) · 1 manuale del regolamento",
    "tags": [
      "senza-competere"
    ],
    "nota_due_scatole": ""
  }
];
